### ISSUE TITLE
Feature Request: Disable Trackpads

### ISSUE THREAD

**Issue by danielh1402** [ayufan/steam-deck-tools#21]
I would like to propose you an improvement for Steam Controller. It is common to accidentally touch the trackpads when we are playing using only the joysticks.

It would be interesting for future updates to add the ability to disable them when using Steam Controller's X360 mode.

Thank you.

**Comment by Raptor2k1** [comment]
I'd like to piggy back off this a little further. When swapping from desktop to 360 controller modes (at the Riva-Tuner UI / high level), I'd personally find it helpful if the overrides for the trackpads (and their click) were disabled in both 360 and SteamInput settings. Reason being that desktop mode gives you what you need to navigate menus using the mouse, etc., and once you've switched over to 360 mode, the general idea is that you should be able to control everything with a controller at that point. 

In the case of 360 controller mode, there's the aforementioned issue of accidental input from brushing the trackpad (which I got occasionally playing Halo Infinite). In the case of SteamInput mode, it's the case of not being able to repurpose the trackpads for other things (such as different options for the trackpad itself, taking advantage of all the other ways you can bind trackpad clicks, etc.), since the current implementation appears to continue to send the mouse movement and left/right click inputs at the same time as anything that's manually bound. In my testing of the latter within WoW, it looks like both inputs were sent (for example, I bound jump/spacebar to right pad click and doing so left-mouse clicked at the same time as jumping, so it'd mess with targeting if I had anything under my cursor when jumping). Same went for left pad click, which I bound to middle mouse, where it triggered both right click and middle click at the same time (which interfered with mouse-over healing skills in-game, since I had different ones bound to left/middle/right clicks respectively).

In my head, I *think* straight up disabling the trackpad overrides (making them work as left/right click and scroll/mouse respectively) in both 360/steaminput controller modes (when not in desktop mode) would resolve both these issues.  Since the touch screen still works regardless, we'd still have some way of doing basic mouse functions and left/right click/scroll even without the SDT's controller's trackpad overrides.

Or maybe it'd be easier / better to have an additional Rivatuner overlay toggle option to enable/disable trackpads (when not in desktop mode), so that folks can easily toggle it to their preference if they need them on/off for any reason? I can maybe think of a few edge cases where you'd want them on in 360 mode, but in steaminput mode I can't really think of a case where you'd want them on (in terms of SDT app overrides/defaults), since you can bind the trackpad functions per-game directly within steam (which is how I'd been handling WoW and similar games).

This suggestion is partly based on how I *think* the program is working under the hood, but the general gist of my line of thought is:
-Touchpad touch/click shouldn't have any commands from SDT bound to them in either 360 or SteamInput modes
-In 360 mode maybe even disable them entirely? Or have a RivaTuner option to do so? (Can still use touchscreen for navigation in a pinch, but eliminates accidental )
-In SteamInput mode, make sure trackpad touch/click aren't tied to any SDT commands, but still allow them to be bound within steam as normal

Thanks again!

**Comment by ayufan** [comment]
@danielh1402 @Raptor2k1 

What do you think about being able to toggle trackpads by hold-press both trackpads for 2s?

The intent is that you can do it quickly in game (in X360 mode), but toggle it back if you wish. You still would have trackpads available while holding STEAM button.

**Comment by danielh1402** [comment]
@ayufan 

Thanks for your answer!
I think it's a very good idea.

**Comment by ayufan** [comment]
@danielh1402 @Raptor2k1 The experimental 0.6.x adds ability to toggle touchpads with long hold press of both trackpads: https://github.com/ayufan/steam-deck-tools/commit/c2ea59d253be56ae1ceb99696a05a57164c2d1f8
